engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    channel: "beta"
    config:
      config: checkstyle.xml
ratings:
  paths: "**.java"
exclude_paths: []
